In [4]:
import numpy as np 
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
%matplotlib inline
import random

In [5]:
dfA = pd.read_csv("historical_RAPTOR_by_player.csv")
dfTemp = dfA.query('season == 2020')

In [6]:
dfTemp.head()

,player_name,player_id,season,poss,mp,raptor_offense,raptor_defense,raptor_total,war_total,war_reg_season,war_playoffs,predator_offense,predator_defense,predator_total,pace_impact
86,Jaylen Adams,adamsja01,2020,43,21,6.207690,7.656298,13.863988,0.180289,0.000000,0.180289,3.989698,3.511923,7.501621,-1.784967
106,Steven Adams,adamsst01,2020,3964,1890,0.315797,1.657408,1.973205,4.542775,4.329823,0.212952,-0.458575,1.632839,1.174265,-0.445224
115,Bam Adebayo,adebaba01,2020,6336,3104,-0.103949,2.226652,2.122704,7.755916,5.311195,2.444721,0.722645,1.480391,2.203036,-0.649095
205,LaMarcus Aldridge,aldrila01,2020,3648,1754,-0.660440,0.777019,0.116579,2.530917,2.530917,0.000000,-0.711668,1.229885,0.518216,-1.367530
221,Kyle Alexander,alexaky01,2020,31,13,-6.054527,-3.622453,-9.676980,-0.047025,-0.047025,0.000000,-2.723092,-4.931522,-7.654614,2.402348

In [7]:
X = np.array(dfTemp[['war_reg_season','war_playoffs']])

In [8]:
def dist(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

In [9]:
def k_func(col1, col2,numclusters):
    X = np.array(dfTemp[[col1,col2]])
    #Initialize
    K = numclusters
    #however...
    x1_coords = [x[0] for x in X]
    centroids = np.empty([K,2])
    for i in range(K):
        centroids[i] = X[random.randint(0,len(X))]
    # centroids = np.random.choice(X[0], K, replace=False)
    dists = [0]*K
    clusters = np.array([-1]*len(X))

    for _ in range(100): #100 steps is fine; or a tolerance/change check.
        #update classifications
        for j in range(len(X)):
            dists = [dist(X[j], cent) for cent in centroids]
            assignment = dists.index(min(dists))
            clusters[j] = assignment
        #update centroids
        for j in range(K):
            centroids[j]=[np.sum(X[clusters==j,0])/len(X[clusters==j,0]),np.sum(X[clusters==j,1])/len(X[clusters==j,1])]
    #initial cluster plot
    fig, ax = plt.subplots(1,1, figsize=(5,5))
    plt.scatter([x[0] for x in X], [x[1] for x in X], c=clusters)
    plt.scatter([x[0] for x in centroids], [x[1] for x in centroids], c='red', marker='+')
    plt.axis([-10, 30, -5, 10])
    plt.xlabel("war_reg_season - 2020")
    plt.ylabel("war_playoffs - 2020")
    col1best = dfTemp[[col1]].max()
    col2best = dfTemp[[col1]].max()
    plt.text(16.7056,3.13679,'James Harden')
    plt.text(9.30393,6.18924, 'Anthony Davis')
    plt.show()
    ###END OPTIONAL

In [10]:
k_func("war_reg_season","war_playoffs",5)

IndexError: index 530 is out of bounds for axis 0 with size 530

In [ ]:
max_war_reg = dfTemp['war_reg_season'].idxmax()
max_war_play = dfTemp['war_playoffs'].idxmax()

In [ ]:
dfA.iloc[max_war_reg]

In [ ]:
dfA.iloc[max_war_play]

In [ ]:
plt.figure(figsize=(12,12))
plt.scatter(X[:, 0], X[:, 1], c=kmeans)

In [ ]:
dfA[['player_name','war_total']]

In [11]:
dfA.nlargest(15, 'war_total')

,player_name,player_id,season,poss,mp,raptor_offense,raptor_defense,raptor_total,war_total,war_reg_season,war_playoffs,predator_offense,predator_defense,predator_total,pace_impact
8746,Michael Jordan,jordami01,1991,7391,3723,9.129036,3.162250,12.291286,28.762877,22.748826,6.014052,9.346199,3.364473,12.710672,-0.109311
7995,LeBron James,jamesle01,2009,6760,3634,9.334994,3.245821,12.580815,28.525259,22.795057,5.730203,9.408782,2.868374,12.277156,-0.344556
8744,Michael Jordan,jordami01,1989,8031,3973,8.297340,2.711836,11.009176,28.015043,23.079246,4.935797,8.195573,2.930561,11.126134,-0.035218
8745,Michael Jordan,jordami01,1990,7832,3871,8.620220,2.217517,10.837736,27.029465,21.754145,5.275320,8.852853,2.488101,11.340954,0.054635
3710,Stephen Curry,curryst01,2016,7053,3314,10.379411,2.108447,12.487858,26.666873,23.659318,3.007555,10.635103,2.712822,13.347925,3.306111
8743,Michael Jordan,jordami01,1988,7498,3738,7.511207,3.677306,11.188513,26.635611,24.355978,2.279633,7.562028,3.953092,11.515120,0.027273
8748,Michael Jordan,jordami01,1993,7438,3850,7.627619,2.779669,10.407288,26.012846,20.290984,5.721862,8.097739,2.932638,11.030377,-0.068663
8747,Michael Jordan,jordami01,1992,7896,4022,6.959557,2.689842,9.649398,25.531369,20.155628,5.375741,7.231270,2.835295,10.066566,-0.159069
8750,Michael Jordan,jordami01,1996,7273,3823,7.646927,2.660800,10.307727,25.472064,20.969545,4.502519,7.834260,2.846782,10.681042,-0.399917
3709,Stephen Curry,curryst01,2015,7192,3439,8.600890,2.437371,11.038262,25.089873,19.914785,5.175088,8.787715,2.657047,11.444762,3.130309
7996,LeBron James,jamesle01,2010,6611,3426,9.196731,2.250084,11.446815,24.812816,21.805025,3.007791,9.158159,1.967559,11.125718,-0.376951
7999,LeBron James,jamesle01,2013,7265,3837,8.529733,1.092302,9.622035,24.219562,18.432110,5.787452,8.668273,1.078148,9.746421,-0.614578
12572,Chris Paul,paulch01,2009,5934,3203,8.195175,3.653223,11.848398,23.824794,23.571882,0.252912,7.845715,4.247403,12.093118,-0.274467
5622,Kevin Garnett,garneke01,2004,7542,4014,4.390076,4.456477,8.846553,23.635042,20.281882,3.353159,4.663240,4.195813,8.859053,-0.857523
16463,Dwyane Wade,wadedw01,2006,7407,3851,6.399515,2.758030,9.157545,23.546339,17.190313,6.356026,6.177999,2.832041,9.010040,-0.184466

In [ ]:
dfA.nlargest(15, 'war_reg_season')

In [ ]:
dfA.nlargest(15, 'war_playoffs')

In [ ]:
dfA.nlargest(15, 'raptor_offense')

In [ ]:
dfA.nlargest(15, 'raptor_defense')

In [ ]:
dfA.nlargest(15, 'war_total')

In [ ]:
max_index = dfA['season'].idxmin()

In [ ]:
dfA.iloc[max_index]

Salary Value

In [12]:
dfSalary = pd.read_csv("Player_Salaries_2018-19.csv")
dfSalary.drop('18/19*', inplace=True, axis=1)
dfSalary.drop('Rank', inplace=True, axis=1)
dfSalary

                   Player       18/19
0           Stephen Curry  37457154.0
1       Russell Westbrook  35665000.0
2            LeBron James  35654150.0
3              Chris Paul  35654150.0
4              Kyle Lowry  32700000.0
5           Blake Griffin  31873932.0
6          Gordon Hayward  31214295.0
7            James Harden  30570000.0
8             Paul George  30560700.0
9             Mike Conley  30521115.0
10           Kevin Durant  30000000.0
11           Paul Millsap  29230769.0
12             Al Horford  28928710.0
13         Damian Lillard  27977689.0
14          DeMar DeRozan  27739975.0
15           Jrue Holiday  26641111.0
16            CJ McCollum  25759766.0
17            Joel Embiid  25467250.0
18         Andrew Wiggins  25467250.0
19           Nikola Jokic  25467250.0
20          Anthony Davis  25434263.0
21           Bradley Beal  25434262.0
22         Andre Drummond  25434262.0
23       Hassan Whiteside  24434262.0
24          Dwight Howard  24256725.0
25           Steven Adams  24157304.0
26  Giannis Antetokounmpo  24157304.0

In [15]:
df2018 = dfA.query('season == 2018')
values = []
war_values = []
for index,row in dfSalary.iterrows():
    name = row['Player']
    salary = row['18/19']
    for indexTwo,rowTwo in df2018.iterrows():
        if rowTwo['player_name'] == name:
            player_value = salary/rowTwo['raptor_total']/100000
            player_war_value = salary/rowTwo['war_total']/100000
            values.append(player_value) 
            war_values.append(player_war_value)
            
dfSalary['Raptor Value'] = values
dfSalary['War Value'] = war_values

In [17]:
# dfSalary.drop('Value', inplace=True, axis=1)
dfSalarySort = dfSalary.sort_values('Raptor Value', ascending = False)
dfSalarySort

                   Player       18/19    War Value  Raptor Value
22         Andre Drummond  25434262.0    66.379571   2950.621600
23       Hassan Whiteside  24434262.0   113.646597   1558.572165
16            CJ McCollum  25759766.0    43.270994    251.087103
14          DeMar DeRozan  27739975.0    43.996286    212.265458
5           Blake Griffin  31873932.0    61.874462    135.433198
8             Paul George  30560700.0    31.163563     93.580961
25           Steven Adams  24157304.0    32.905469     92.634661
21           Bradley Beal  25434262.0    28.047471     90.584116
9             Mike Conley  30521115.0   261.703030     89.652217
1       Russell Westbrook  35665000.0    30.118896     80.520390
12             Al Horford  28928710.0    28.033853     70.653674
2            LeBron James  35654150.0    20.477098     61.819321
4              Kyle Lowry  32700000.0    27.211956     61.155841
15           Jrue Holiday  26641111.0    22.079753     60.803002
17            Joel Embiid  25467250.0    31.783300     58.865731
10           Kevin Durant  30000000.0    23.145935     58.140167
0           Stephen Curry  37457154.0    31.616597     49.561294
20          Anthony Davis  25434263.0    19.851453     48.318607
19           Nikola Jokic  25467250.0    24.785810     46.522862
13         Damian Lillard  27977689.0    21.844595     46.418773
26  Giannis Antetokounmpo  24157304.0    18.712893     43.535615
3              Chris Paul  35654150.0    26.107385     41.600433
7            James Harden  30570000.0    14.608507     30.364225
6          Gordon Hayward  31214295.0 -9460.493870    -19.911993
24          Dwight Howard  24256725.0   442.884170   -104.713996
18         Andrew Wiggins  25467250.0    74.609161   -409.698744
11           Paul Millsap  29230769.0   202.939146  -1015.980674